add html&css
DenysShchypt/life_in_chocolate pull request #19
Opened 2023-06-02 15:54 UTC by Olegmkv

2023-06-04 20:30 UTC, DenysShchypt requested changes

2023-06-04 20:30 UTC, DenysShchypt commented on src/css/footer.css
> +@media only screen and (min-width: 768px) {
розміри зайві. відповідь в html

2023-06-04 20:30 UTC, DenysShchypt commented on src/partials/footer.html
> +              <svg class="footer-socials-icon" width="22" height="22">
потрібно зробити дві svg в посиланні і приховувати іх за допомогою обо опасіті, або краще displey: none

2023-06-04 20:30 UTC, DenysShchypt commented on src/css/footer.css
> +@media only screen and (min-width: 768px) {
для чого цей margin-bottom: 0;? він на наступних брекпоінтах нічого не робить і по друге так невірно робити (опис є в конспекті)

2023-06-04 20:30 UTC, DenysShchypt commented on src/css/footer.css
> +.footer-nav-item:not(:last-child) {
тут медіа запит max-widht 767px

2023-06-04 21:15 UTC, Olegmkv commented on src/css/footer.css
> +    letter-spacing: -0.02em;
leter прибрав

2023-06-05 08:38 UTC, Olegmkv commented on src/partials/footer.html
> +        <address class="footer-adr">
прибрав

2023-06-05 09:19 UTC, Olegmkv commented on src/css/footer.css
> +.footer-nav-item:not(:last-child) {
виправив

2023-06-05 09:22 UTC, Olegmkv commented on src/css/footer.css
> +@media only screen and (min-width: 768px) {
виправив

2023-06-05 11:42 UTC, Olegmkv commented on src/css/footer.css
> +    align-items: flex-start;
align-items: flex-start прибрав

2023-06-05 11:56 UTC, Olegmkv commented on src/partials/footer.html
> +            <li class="footer-adr-item">
залишив, використовую для марджин-боттом крім останнього елементу списку

2023-06-05 11:59 UTC, Olegmkv commented on src/css/footer.css
> +    width: 22px;
прибрав, переробив через окремі свг, так дійсно краще

2023-06-05 12:21 UTC, Olegmkv commented on src/css/footer.css
> +        width: 300px;
замінив на мінімальні розміри блоку для таблету і дектопу по макету ; при збільшенні довжини емайлу контент не буде випадати за сторінку, спочатку займе місце до іконок справа, а потім розширює весь блок вліво, до слогану.

2023-06-05 20:01 UTC, Olegmkv commented on src/css/footer.css
> +    width: 100%;
прибрав

2023-06-05 20:28 UTC, Olegmkv commented on src/css/footer.css
> +        justify-content: space-between;
то я спочатку задав невірну ширину цьому блоку(для симетрії), зараз це вже виправлено, з space-between гнучкіше, як на мене

2023-06-05 23:32 UTC, Olegmkv commented on src/css/footer.css
> +    height: 100%;
повидаляв

2023-06-05 23:32 UTC, Olegmkv commented on src/css/footer.css
> +    width: 100%;
повидаляв

2023-06-05 23:32 UTC, Olegmkv commented on src/css/footer.css
> +    height: 22px;
повидаляв

2023-06-06 08:38 UTC, DenysShchypt approved these changes

2023-06-06 08:38 UTC, merged