Feauteres/our products
DenysShchypt/life_in_chocolate pull request #27
Opened 2023-06-03 01:35 UTC by galychka

Для Swiper потрібно 
//Вставити в index.html після головного Title це посилання://

<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"
/>  

//Перед закриваючим тегом боді: //

<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>  

//В папці Js зробити папку swiper.js і вставити//

const swiper = new Swiper('.swiper', {
  // Optional parameters
  direction: 'horizontal',
  loop: true,

  // If we need pagination
  pagination: {
    el: '.swiper-pagination',
    clickable: true,
  },

  // Navigation arrows
  navigation: {
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  },

  // And if we need scrollbar
  scrollbar: {
    el: '.swiper-scrollbar',
  },
});

2023-06-05 19:02 UTC, batalova-kira commented on src/partials/our-products.html
> +      <h2 class="title-our-prodacts title">OUR <span class="title-acent-color">PRODUCTS</span></h2>
OUR PRODUCTS маленькими літерами, бо велики їх робе text-transform: uppercase;

2023-06-05 19:08 UTC, batalova-kira commented on src/css/our-products.css
> +    background: #FAFAFA;
так само, кольори повинни бути вказани через змінну var( )

2023-06-05 22:56 UTC, DenysShchypt requested changes
Там у вас є якасть проблема з картками, поки маржини. на секції завжди задаються тільки падінги. завтра виришимо по картках, там щось розміри незбігаються. А взагалі, дуже хороша робота)

2023-06-05 22:56 UTC, DenysShchypt commented on src/css/our-products.css
> + margin-bottom: 72px;
падинг ботом

2023-06-05 22:56 UTC, DenysShchypt commented on src/css/our-products.css
> +        margin-bottom: 168px;
падинг ботом

2023-06-05 22:56 UTC, DenysShchypt commented on src/css/our-products.css
> +        margin-bottom: 128px;
падинг ботом

2023-06-06 09:21 UTC, DenysShchypt approved these changes

2023-06-06 09:22 UTC, merged